# Indian E-Commerce Customer Behavior Analysis

## Notebook 01: Data Cleaning

### Objective
Prepare the raw e-commerce dataset for downstream analysis in SQL, Python, Excel, and Power BI by ensuring data quality, consistency, and usability.
### Tasks
- Load the raw dataset
- Inspect data structure
- Check data types
- Identify missing values
- Detect duplicate records
- Validate categorical values
- Export cleaned dataset

### Dataset
Indian E-Commerce Customer Behavior & Purchase

### Tools
- Python
- Pandas
- NumPy

### Output
# `data/cleaned/indian_ecommerce_cleaned.csv`

In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../data/raw/indian_ecommerce.csv")

In [8]:
df.head()

,customer_id,session_id,visit_date,device_type,user_type,marketing_channel,product_id,product_category,unit_price,quantity,...,review_text,review_helpful_votes,payment_method,visit_day,visit_month,visit_weekday,visit_season,session_duration_bucket,revenue_normalized,location
0,1803,0,28-11-2024,2,1,2,894,6,651.57,1,...,1,0,1,28,11,3,0,Long,0.000000,209
1,7964,1,25-09-2024,2,0,4,844,2,945.27,4,...,1,0,2,25,9,2,0,Long,0.000000,213
2,6890,2,31-05-2024,1,1,0,865,0,400.44,4,...,1,0,2,31,5,4,1,Short,0.000000,10
3,4949,3,30-01-2024,1,0,2,851,3,1268.54,2,...,10,4,1,30,1,1,3,Very Long,0.305504,46
4,4896,4,25-02-2024,1,1,5,794,3,880.81,3,...,1,0,1,25,2,6,3,Very Short,0.000000,118

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              25000 non-null  int64
 1   session_id               25000 non-null  int64
 2   visit_date               25000 non-null  object
 3   device_type              25000 non-null  int64
 4   user_type                25000 non-null  int64
 5   marketing_channel        25000 non-null  int64
 6   product_id               25000 non-null  int64
 7   product_category         25000 non-null  int64
 8   unit_price               25000 non-null  float64
 9   quantity                 25000 non-null  int64
 10  discount_percent         25000 non-null  int64
 11  discount_amount          25000 non-null  float64
 12  revenue                  25000 non-null  float64
 13  pages_viewed             25000 non-null  int64
 14  time_on_site_sec         25000 non-null  int64
 15  added_to_cart            25000 non-null  int64
 16  purchased                25000 non-null  int64
 17  cart_abandoned           25000 non-null  int64
 18  rating                   25000 non-null  int64
 19  review_text              25000 non-null  int64
 20  review_helpful_votes     25000 non-null  int64
 21  payment_method           25000 non-null  int64
 22  visit_day                25000 non-null  int64
 23  visit_month              25000 non-null  int64
 24  visit_weekday            25000 non-null  int64
 25  visit_season             25000 non-null  int64
 26  session_duration_bucket  25000 non-null  object
 27  revenue_normalized       25000 non-null  float64
 28  location                 25000 non-null  int64
dtypes: float64(4), int64(23), object(2)
memory usage: 5.5+ MB

In [10]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 25000
Columns: 29

In [11]:
df.columns.tolist()

['customer_id',
 'session_id',
 'visit_date',
 'device_type',
 'user_type',
 'marketing_channel',
 'product_id',
 'product_category',
 'unit_price',
 'quantity',
 'discount_percent',
 'discount_amount',
 'revenue',
 'pages_viewed',
 'time_on_site_sec',
 'added_to_cart',
 'purchased',
 'cart_abandoned',
 'rating',
 'review_text',
 'review_helpful_votes',
 'payment_method',
 'visit_day',
 'visit_month',
 'visit_weekday',
 'visit_season',
 'session_duration_bucket',
 'revenue_normalized',
 'location']

In [12]:
df.isnull().sum()

customer_id                0
session_id                 0
visit_date                 0
device_type                0
user_type                  0
marketing_channel          0
product_id                 0
product_category           0
unit_price                 0
quantity                   0
discount_percent           0
discount_amount            0
revenue                    0
pages_viewed               0
time_on_site_sec           0
added_to_cart              0
purchased                  0
cart_abandoned             0
rating                     0
review_text                0
review_helpful_votes       0
payment_method             0
visit_day                  0
visit_month                0
visit_weekday              0
visit_season               0
session_duration_bucket    0
revenue_normalized         0
location                   0
dtype: int64

In [13]:
df.duplicated().sum()

0

In [14]:
df.describe(include="all")

,customer_id,session_id,visit_date,device_type,user_type,marketing_channel,product_id,product_category,unit_price,quantity,...,review_text,review_helpful_votes,payment_method,visit_day,visit_month,visit_weekday,visit_season,session_duration_bucket,revenue_normalized,location
count,25000.000000,25000.000000,25000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,...,25000.00000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000,25000.000000,25000.00000
unique,NaN,NaN,365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
top,NaN,NaN,20-09-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very Short,NaN,NaN
freq,NaN,NaN,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6270,NaN,NaN
mean,5479.930600,12499.500000,NaN,0.705040,0.551280,2.514040,449.107000,3.495240,782.319010,2.489040,...,1.67488,5.52080,2.483160,15.714520,6.510520,2.980800,1.504400,NaN,0.051290,111.70692
std,2593.544596,7217.022701,NaN,0.639543,0.497373,1.704934,259.513787,2.285053,476.612168,1.114563,...,1.98673,12.33629,1.709501,8.796338,3.457925,1.992554,1.117475,NaN,0.129591,65.07079
min,1000.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,50.050000,1.000000,...,0.00000,0.00000,0.000000,1.000000,1.000000,0.000000,0.000000,NaN,0.000000,0.00000
25%,3234.000000,6249.750000,NaN,0.000000,0.000000,1.000000,225.000000,2.000000,395.222500,1.000000,...,1.00000,0.00000,1.000000,8.000000,3.000000,1.000000,1.000000,NaN,0.000000,55.00000
50%,5482.000000,12499.500000,NaN,1.000000,1.000000,2.000000,448.000000,4.000000,691.725000,2.000000,...,1.00000,0.00000,2.000000,16.000000,7.000000,3.000000,2.000000,NaN,0.000000,111.00000
75%,7715.000000,18749.250000,NaN,1.000000,1.000000,4.000000,675.000000,5.000000,1096.842500,3.000000,...,1.00000,0.00000,4.000000,23.000000,10.000000,5.000000,3.000000,NaN,0.000000,169.00000
max,9998.000000,24999.000000,NaN,2.000000,1.000000,5.000000,898.000000,7.000000,1999.830000,4.000000,...,10.00000,49.00000,5.000000,31.000000,12.000000,6.000000,3.000000,NaN,1.000000,224.00000

In [15]:
df.dtypes

customer_id                  int64
session_id                   int64
visit_date                  object
device_type                  int64
user_type                    int64
marketing_channel            int64
product_id                   int64
product_category             int64
unit_price                 float64
quantity                     int64
discount_percent             int64
discount_amount            float64
revenue                    float64
pages_viewed                 int64
time_on_site_sec             int64
added_to_cart                int64
purchased                    int64
cart_abandoned               int64
rating                       int64
review_text                  int64
review_helpful_votes         int64
payment_method               int64
visit_day                    int64
visit_month                  int64
visit_weekday                int64
visit_season                 int64
session_duration_bucket     object
revenue_normalized         float64
location                     int64
dtype: object

In [16]:
categorical_cols = [
    "device_type",
    "user_type",
    "marketing_channel",
    "product_category",
    "payment_method",
    "visit_weekday",
    "visit_season",
    "session_duration_bucket"
]

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].unique())

device_type
[2 1 0]

user_type
[1 0]

marketing_channel
[2 4 0 5 1 3]

product_category
[6 2 0 3 7 4 1 5]

payment_method
[1 2 5 4 3 0]

visit_weekday
[3 2 4 1 6 0 5]

visit_season
[0 1 3 2]

session_duration_bucket
['Long' 'Short' 'Very Long' 'Very Short']

In [17]:
numeric_cols = [
    "unit_price",
    "quantity",
    "discount_percent",
    "discount_amount",
    "revenue",
    "pages_viewed",
    "time_on_site_sec",
    "rating"
]

(df[numeric_cols] < 0).sum()

unit_price          0
quantity            0
discount_percent    0
discount_amount     0
revenue             0
pages_viewed        0
time_on_site_sec    0
rating              0
dtype: int64

In [18]:
df["visit_date"] = pd.to_datetime(df["visit_date"])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              25000 non-null  int64
 1   session_id               25000 non-null  int64
 2   visit_date               25000 non-null  datetime64[ns]
 3   device_type              25000 non-null  int64
 4   user_type                25000 non-null  int64
 5   marketing_channel        25000 non-null  int64
 6   product_id               25000 non-null  int64
 7   product_category         25000 non-null  int64
 8   unit_price               25000 non-null  float64
 9   quantity                 25000 non-null  int64
 10  discount_percent         25000 non-null  int64
 11  discount_amount          25000 non-null  float64
 12  revenue                  25000 non-null  float64
 13  pages_viewed             25000 non-null  int64
 14  time_on_site_sec         25000 non-null  int64
 15  added_to_cart            25000 non-null  int64
 16  purchased                25000 non-null  int64
 17  cart_abandoned           25000 non-null  int64
 18  rating                   25000 non-null  int64
 19  review_text              25000 non-null  int64
 20  review_helpful_votes     25000 non-null  int64
 21  payment_method           25000 non-null  int64
 22  visit_day                25000 non-null  int64
 23  visit_month              25000 non-null  int64
 24  visit_weekday            25000 non-null  int64
 25  visit_season             25000 non-null  int64
 26  session_duration_bucket  25000 non-null  object
 27  revenue_normalized       25000 non-null  float64
 28  location                 25000 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(23), object(1)
memory usage: 5.5+ MB

C:\Users\harsh\AppData\Local\Temp\ipykernel_6632\1775926940.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["visit_date"] = pd.to_datetime(df["visit_date"])

In [19]:
print(df.shape)

df.head()

(25000, 29)

,customer_id,session_id,visit_date,device_type,user_type,marketing_channel,product_id,product_category,unit_price,quantity,...,review_text,review_helpful_votes,payment_method,visit_day,visit_month,visit_weekday,visit_season,session_duration_bucket,revenue_normalized,location
0,1803,0,2024-11-28,2,1,2,894,6,651.57,1,...,1,0,1,28,11,3,0,Long,0.000000,209
1,7964,1,2024-09-25,2,0,4,844,2,945.27,4,...,1,0,2,25,9,2,0,Long,0.000000,213
2,6890,2,2024-05-31,1,1,0,865,0,400.44,4,...,1,0,2,31,5,4,1,Short,0.000000,10
3,4949,3,2024-01-30,1,0,2,851,3,1268.54,2,...,10,4,1,30,1,1,3,Very Long,0.305504,46
4,4896,4,2024-02-25,1,1,5,794,3,880.81,3,...,1,0,1,25,2,6,3,Very Short,0.000000,118

In [20]:
df.to_csv("../data/cleaned/indian_ecommerce_cleaned.csv", index=False)

## Summary

Data quality assessment was completed successfully.

### Findings

- No missing values were found.
- No duplicate records were identified.
- Data types were validated.
- Numerical columns contained no invalid negative values.
- Categorical values were consistent.
- Visit dates were converted to datetime format.
- The cleaned dataset was exported for SQL analysis and Power BI.